#! /bin/bash -l
#
# Maurice Gonzenbach, 30.11.12, ETH Zurich
# runs make with different compilers for all blas testing routines

# clear all modules
module purge

# load gnu programming environment
module load PrgEnv-gnu
make sci PRGENV=gnu
module switch xt-libsci acml
make acml PRGENV=gnu
